### ISSUE TITLE
Suggestion: Don't report current temperature for controllers that don't provide the info

### ISSUE THREAD

**Issue by mbdmbd** [mantorok1/homebridge-rinnai-touch-plugin#1]
Not sure if this is an easy or complicated ask, and certainly isn't high priority.

I believe that some Brivis controllers like the NC-6 do not offer the current temperature (either to the official app or to queries made to them). As a result, the Home app always reports a current temperature of 0.0 degrees. 

![image](https://user-images.githubusercontent.com/12741220/83578903-32cbd100-a57b-11ea-865c-da2b729c7745.png)

Just a suggestion that if when querying the system, if the response is likely to be one from a controller that doesn't give the information, that the plugin doesn't attempt to show/display the value.

P.S. Thanks for the incredible work on the plugin.

**Comment by mantorok1** [comment]
Thanks @mbdmbd, I have tried to somehow blank out the temperature if the WiFi module is unable to supply the current temp however was unable to find a way to do this. I tried setting it to undefined, null, NaN & Infinity but in each case it would just display 0.0 degrees.  Looks like its a limitation of Homebridge.
